### ISSUE TITLE
Add primitive-box

### ISSUE THREAD

**Issue by vorg** [dmnsgn/primitive-geometry#6]
What about adding seamless box https://github.com/vorg/primitive-box useful for AABB rendering.

**Comment by dmnsgn** [comment]
It's actually in the deps, just not exported. I hesitated as it doesn't have uv/normals but heh since it's there.

**Comment by dmnsgn** [comment]
Fixed (box + circle) cb8490106cbf714c66fb8bb625210ad6b20c2d2f
